### ISSUE TITLE
Giving some love...

### ISSUE THREAD

**Issue by jarroddavis68** [Coldzer0/ImGui-Pascal#2]
Hello! I've featured your repository in the Delphi Game Development Facebook group. If you haven't joined yet, consider becoming a part of the community.

https://www.facebook.com/groups/322814267886893/posts/2650837968417833/

**Comment by Coldzer0** [comment]
Thanks for the share and support.
But unfortunately, I don't use Facebook. 

I'll keep adding more APIs for the ImGui Class and other demos to help people using it.

**Comment by jarroddavis68** [comment]
> Thanks for the share and support. But unfortunately, I don't use Facebook.
> 
Ahh ok.
> I'll keep adding more APIs for the ImGui Class and other demos to help people using it.
Cool, I keep checking in and keep the group updated.

How are you handling high DPI and moving between monitors with different DPIs?

**Comment by Coldzer0** [comment]
DPI support is on my TODO list.
There's a starting point of DPI support on https://github.com/ocornut/imgui/blob/docking/backends/imgui_impl_win32.cpp

I'm still paying with some Ideas for ideal DPI support on multiOS.

Feel free to reach me on Discord. I'm very active there.
My Discord ID: `Coldzer0`

**Comment by jarroddavis68** [comment]
This is what I am currently doing:

1. when the dpi changes, I calc new dpi and scale
2. I shutdown/restart cimgui
3. load a custom font size * scale (cache this font base on dpi and just reuse on the same dpi)
4. scale the styles by the new scale (ImGuiStyle_ScaleAllSizes). Doing this after a restart will resize all the windows to the appropriate size. 

As I move the window across monitors with different DPIs, I get a scaled imgui without the blurry. Not ideal but gives the best results as is and way better than calling IO.GlobalFontScale, which is simple, but can look terrible.

**Comment by Coldzer0** [comment]
> This is what I am currently doing:
> 
> 1. when the dpi changes, I calc new dpi and scale
> 2. I shutdown/restart cimgui
> 3. load a custom font size * scale (cache this font base on dpi and just reuse on the same dpi)
> 4. scale the styles by the new scale (ImGuiStyle_ScaleAllSizes). Doing this after a restart will resize all the windows to the appropriate size.
> 
> As I move the window across monitors with different DPIs, I get a scaled imgui without the blurry. Not ideal but gives the best results as is and way better than calling IO.GlobalFontScale, which is simple, but can look terrible.

Nice approach for a single window, but the problem with this one is if you are using Multi-viewports, you have to close all opened windows and reinit in the same state.

I'll keep this repo updated whenever I get a working solution.
