### ISSUE TITLE
Vulkan binding

### ISSUE THREAD

**Issue by tigrazone** [Coldzer0/ImGui-Pascal#4]
Is it planned?
I mean w/o use of sdl or tons of dlls

**Comment by Coldzer0** [comment]
Yes, It is on my TODO list.

But I'm first making some changes to include the backend implementation code for each library in the imgui lib itself.
So we would have an "imgui_vulkan.a", "imgui_glfw.a"; etc..

Maintaining a backend code in Pascal would be a waste of time, as the code has already been done in IMGUI and is up to date.

I'll start next week as I'm busy at the moment.

**Comment by tigrazone** [comment]
I cant find pascal bindings w/o SDL. but SDL dont needed.
c++ can use imGui with vulkan but Pascalers...
